"""init

Revision ID: cc906795daac
Revises: 110e7d8e456b
Create Date: 2024-03-26 10:53:45.517384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc906795daac'
down_revision: Union[str, None] = '110e7d8e456b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('data_completion', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tasks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Tasks_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_completion', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Tasks_pkey')
    )
    op.drop_table('tasks')
    # ### end Alembic commands ###
